### ISSUE TITLE
ios 8 以上和以下这条判断一样

### ISSUE THREAD

**Issue by iScript** [jpush/jpush-swift-demo#2]
JPUSHService.registerForRemoteNotificationTypes(UIUserNotificationType.Badge.rawValue | UIUserNotificationType.Badge.rawValue | UIUserNotificationType.Alert.rawValue , categories: nil)

**Comment by huangminlinux** [comment]
ios 8 以前 参数categories 必须为nil  ，这个注释没写清楚，已添加注释
